### PR TITLE
Add negative scanner tests and update to use Sinon

### PR DESCRIPTION
**Pull request by akrs**
This has coverage for all the loops in our scanner, to prevent nasty infinite loop bugs. I've also squashed those bugs.

I've also switched the syntax checking to use Sinon instead of our previous checking of error.count. Hopefully you can figure it out. If not, we can go over this tomorrow afternoon.

### CODE REVIEW

**Comment by gastyrd** [comment]
Looked into sinon-chai and its assertions, looks pretty good, far more elegant that our previous rudimentary syntax checking. +1

**Comment by joaquinloustau** [comment]
I'm glad we don't have to use the error count anymore. I felt like that would get back to us at some point. We are testing for infinite loops with the time-out function right? I feel like that is dangerous, but I am not sure about workarounds for that. Don´t want to close it until @stephenscottsmith or @mcoccia  look at it, in case they come up with something.

**Comment by akrs** [comment]
Unfortunately, it isn’t possible to catch the loop with the timeout. I thought it would be, but it isn’t. Even if we can’t catch it, the build will error out if there’s a loop, so that should be our cue that something is wrong.

**Comment by joaquinloustau** [comment]
So that mean we can´t really identify an infinite loop from another kind of error, right? I think that´s fine, I don´t know how important it is to test for infinite loops as compared to errors in general. Opinions?

**Comment by akrs** [comment]
It's important to check for both. But in this case, a failure won't look too different than another failing test. Check #7 for an example of an infinite loop test failing.

**Pull request merged**
